services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  # pgdatabase:
  #   image: postgres:13
  #   environment:
  #     - POSTGRES_USER=root 
  #     - POSTGRES_PASSWORD=root
  #     - POSTGRES_DB=sub_domains
  #   volumes:
  #     - "./sub_domains_postgres_data:/var/lib/postgresql/data:rw"
  #   ports:
  #     - "5432:5432"
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=root
  #   ports:
  #     - 8080:80
  # mongodb:
  #   image: mongo
  #   restart: always
  #   container_name: mongodb
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   ports:
  #     - '27017:27017'
  #   volumes:
  #     - ../mongo-data:/data/db
  # mongo-express:
  #   image: mongo-express:0.54.0
  #   restart: always
  #   container_name: mongo_ui
  #   environment:
  #     ME_CONFIG_MONGODB_URL: "mongodb://root:example@mongo:27017/"
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #   ports:
  #     - 8081:8081
  mongodb:
    image:  mongo:4.4.17-focal
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
  
